<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

---

## Домашнее задание 2: библиотека Numpy и линейная алгебра. Решение


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.45153753 0.87509056 0.36211245 ... 0.45999815 0.88237839 0.06302987]
 [0.73056127 0.48189949 0.01861012 ... 0.83326722 0.23726454 0.76906658]
 [0.54508869 0.36463571 0.9257959  ... 0.2010756  0.3417138  0.23345184]
 ...
 [0.91031235 0.73759171 0.2676726  ... 0.26496864 0.48095345 0.39708539]
 [0.77103124 0.90250193 0.35726107 ... 0.16540669 0.70463903 0.62119001]
 [0.61927498 0.52700128 0.06533169 ... 0.1308348  0.05435711 0.60264696]]
[[0.68908484 0.88868345 0.85670873 ... 0.02624385 0.18916156 0.52370028]
 [0.63785978 0.53348461 0.63111486 ... 0.46657823 0.64789328 0.88571087]
 [0.28524072 0.47938485 0.89283795 ... 0.56682784 0.18682155 0.16610861]
 ...
 [0.53224513 0.02305852 0.00834829 ... 0.72736583 0.50358264 0.65954781]
 [0.6858598  0.88315785 0.43900484 ... 0.41168538 0.62920525 0.30485607]
 [0.52316819 0.89406156 0.75671444 ... 0.68196968 0.07268901 0.39565747]]


In [7]:
def mult(a, b):
    # здесь напишите перемножение матриц без 
    # использования NumPy и выведите результат
    c = [[0 for _ in range(len(a))] for _ in range(len(b[0]))]
    for i in range(len(a)):
        for j in range(len(b)):
            for k in range(len(a[0])):
                c[i][j] += a[i][k] * b[k][j]
    return c

In [8]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    return a @ b

In [9]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

Wall time: 657 ms


In [6]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

Wall time: 10 ms


In [8]:
np.abs(np.array(M1) - M2).sum()

1.7674750552032492e-11

### Задание 2
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  
Аналогично -- с помощью библиотеки **NumPy** и без нее. Сравните скорость.

In [9]:
# функция, решающая задачу с помощью NumPy
def sec_av(A):
    return np.cumsum(A) / np.arange(1, len(A)+1)

In [10]:
# функция без NumPy
def stupid_sec_av(A):
    S = [sum(A[:i+1])/(i+1) for i in range(len(A))]
    return S

In [11]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# вторая функция должна работать ~ в 50 раз быстрее
A = sps.uniform.rvs(size=10**3) 

%time S1 = stupid_sec_av(A)
%time S2 = sec_av(A)
# проверим корректность (последовательности должны совпадать, т.е. разность равна 0):
np.abs(S1 - S2).sum()

Wall time: 68 ms
Wall time: 0 ns


0.0

### Задание 3

Пусть задан некоторый массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все четные элементы исходного массива нужно возвести в куб и записать в обратном порядке относительно позиций этих элементов. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [10]:
# функция, решающая задачу с помощью NumPy
def transformation(X, a=1):
    N = np.array(X[::-1])
    N[1::2] = a
    N[::2] = N[::2] ** 3
    return np.hstack((np.array(X) , N))

In [11]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a=1):
    N = X[::-1]
    N[1::2] = [a for _ in range(len(N[1::2]))]
    N[::2] = [x**3 for x in N[::2]]
    return X + N

In [12]:
X = [i for i in range(10, 1000, 10)]
# здесь код должен быть эффективнее примерно в 20 раз. 
%time S1 = stupid_transformation(X)
%time S2 = transformation(X)
# проверим корректность:
np.abs(S1 - S2).sum()

Wall time: 2.01 ms
Wall time: 18 ms


0

Почему методы ***numpy*** оказываются эффективнее (можно гуглить)?

Что вы можете сказать о скорости вычислений в NumPy? Ответ обоснуйте.

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 4

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [18]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.09612389 0.87799289 0.51076262] [0.50494049 0.63206468 0.56311593]


In [19]:
def stupid_scalar_product(a,b):
    return sum([x * y for (x, y) in zip(a, b)])

In [28]:
def numpy_scalar_product(a,b):
    return np.dot(a, b)

In [29]:
%time product_1 = stupid_scalar_product(a,b)
%time product_2 = numpy_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

Wall time: 0 ns
Wall time: 14 ms


0.0

### Задание 5*

Нужно написать матричное произведение БЕЗ циклов и БЕЗ символа @, БЕЗ `np.dot` и вообще БЕЗ какой-либо вспомогательной функции из `numpy`, то есть пользуясь только индексированием, взятем суммы по нужным осям и поэлементным произведенем (да, это возможно). Рекомендуем гуглить по запросу "NumPy broadcasting"

In [30]:
def cool_matrix_product(A, B):
    # налейте чаю, удобно присядьте и просто осознайте это :)
    # (на самом деле просто распишите, что получается про numpy broadcasting)
    return (A[:,:, None] * B[None,:,:]).sum(axis=1)  

In [40]:
A = np.random.sample((3, 3))
B = np.random.sample((3, 3))

In [41]:
np.sum(A@B - cool_matrix_product(A, B), axis=0)

array([0.00000000e+00, 0.00000000e+00, 5.55111512e-17])

(машинный ноль)

In [63]:
A[None,:,:]

array([[[0.83578482, 0.07938553, 0.06767209],
        [0.38278945, 0.74783822, 0.33897517],
        [0.17628183, 0.29827363, 0.25995047]]])

In [51]:
A[:,:,None].shape

(3, 3, 1)

In [50]:
A.shape

(3, 3)

In [54]:
C = A[:,:, None] * B[None,:,:]
C.shape

(3, 3, 3)

In [55]:
C

array([[[0.23255383, 0.09489734, 0.52261213],
        [0.01167119, 0.06734236, 0.07675863],
        [0.00769869, 0.06501313, 0.01590652]],

       [[0.10650966, 0.04346298, 0.23935636],
        [0.10994652, 0.6343875 , 0.72309189],
        [0.0385634 , 0.32565625, 0.07967709]],

       [[0.04904972, 0.02001553, 0.11022816],
        [0.04385193, 0.25302406, 0.28840361],
        [0.02957318, 0.24973657, 0.06110211]]])

In [62]:
C.sum(axis=1) 

array([[0.25192372, 0.22725283, 0.61527727],
       [0.25501957, 1.00350673, 1.04212533],
       [0.12247483, 0.52277616, 0.45973387]])